# Generated by Django 4.2.11 on 2024-03-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNumner',
            new_name='phoneNumber',
        ),
    ]
