# Generated by Django 4.2.11 on 2024-03-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_phonenumner_contact_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='linkPrecedence',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], max_length=10),
        ),
    ]
